/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/ActionBar.vue')['default']
    AddEditCategoryModal: typeof import('./components/AddEditCategoryModal.vue')['default']
    AddEditMenuItemsModal: typeof import('./components/AddEditMenuItemsModal.vue')['default']
    AddEditResturantModal: typeof import('./components/AddEditResturantModal.vue')['default']
    Admin: typeof import('./pages/admin/Admin.vue')['default']
    AdminActionBar: typeof import('./components/AdminActionBar.vue')['default']
    AdminLayout: typeof import('./layouts/AdminLayout.vue')['default']
    App: typeof import('./App.vue')['default']
    AuthLayout: typeof import('./layouts/AuthLayout.vue')['default']
    BaseButton: typeof import('./components/ui/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./components/ui/BaseCheckbox.vue')['default']
    BaseDatePicker: typeof import('./components/ui/BaseDatePicker.vue')['default']
    BaseDropdown: typeof import('./components/ui/BaseDropdown.vue')['default']
    Baseinput: typeof import('./components/ui/Baseinput.vue')['default']
    BaseModal: typeof import('./components/ui/BaseModal.vue')['default']
    BaseTextArea: typeof import('./components/ui/BaseTextArea.vue')['default']
    BreadCrums: typeof import('./components/BreadCrums.vue')['default']
    CartPage: typeof import('./pages/user/CartPage.vue')['default']
    Checkout: typeof import('./pages/user/Checkout.vue')['default']
    CommonDataTable: typeof import('./components/CommonDataTable.vue')['default']
    DeleteResurantModal: typeof import('./components/DeleteResurantModal.vue')['default']
    DropdownMenu: typeof import('./components/DropdownMenu.vue')['default']
    EnableDisableCategoryModal: typeof import('./components/EnableDisableCategoryModal.vue')['default']
    ForgotPassword: typeof import('./pages/shared/ForgotPassword.vue')['default']
    Home: typeof import('./pages/Home.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    Login: typeof import('./pages/shared/Login.vue')['default']
    MenuManagement: typeof import('./pages/admin/MenuManagement.vue')['default']
    MenuPage: typeof import('./pages/user/MenuPage.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NewPassword: typeof import('./pages/shared/NewPassword.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    OrderConfirmation: typeof import('./pages/user/OrderConfirmation.vue')['default']
    OrderDetailsModal: typeof import('./components/OrderDetailsModal.vue')['default']
    OrderManagement: typeof import('./pages/admin/OrderManagement.vue')['default']
    OrderManagmentTable: typeof import('./components/OrderManagmentTable.vue')['default']
    OtpVerification: typeof import('./pages/shared/OtpVerification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SuperAdmin: typeof import('./pages/superAdmin/SuperAdmin.vue')['default']
    SuperAdminLayout: typeof import('./layouts/SuperAdminLayout.vue')['default']
    Switch: typeof import('./components/ui/Switch.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    Toaster: typeof import('./components/Toaster.vue')['default']
    UserCard: typeof import('./components/UserCard.vue')['default']
    UserLayout: typeof import('./layouts/UserLayout.vue')['default']
    UserNavbar: typeof import('./components/UserNavbar.vue')['default']
    UserProfile: typeof import('./pages/shared/UserProfile.vue')['default']
  }
}
